### PR TITLE
Use base64url decoding in JWT

### PR DESCRIPTION
**Pull request by middagj**
### Short description
I was busy trying to create something with transip api when I now and then received a `could not decode token, invalid base64` error. It happens every time when a `_` is in the payload of the JWT. The JWT is not encoded with normal base64, but with base64url as specified in [RFC 7519](https://tools.ietf.org/html/rfc7519). I changed the code and added a test.

### Checklist

- [x] I read the [CONTRIBUTING.md](https://github.com/transip/gotransip/blob/master/CONTRIBUTING.md) document
- [x] This code actually compiles
- [x] This code solves my problem
- [x] I've updated the inline documentation
- [x] I added or modified test(s) to prevent this issue from ever occurring again

### CODE REVIEW

**Comment by middagj** [comment]
Sorry for all the requests, btw :)

**Comment by middagj** [comment]
@svenwiltink any idea when this can be released? This is blocking us from successfully integrating with TransIP

**Comment by SaltyJahmale** [comment]
+1.
I'm also having issues with the decoding.

**Comment by dionbosschieter** [comment]
Hey,

Thanks for your pull request and sorry for the late response. I took a look at token builder at our side and you are right, it is generating base64url encoded strings, we definitely overlooked this one.

**Pull request merged**
